# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
name: Cargo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# LINT.IfChange
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Test Cargo project
      run: >
        cargo test --verbose --locked --workspace --no-fail-fast
        --exclude '*_sys'
        --exclude 'rs_bindings_from_cc*'
    - name: Build not-yet-testable Cargo crates
      run: >
        cargo build --verbose --locked --workspace
        --exclude '*_sys'
        --exclude=rs_bindings_from_cc
        --exclude=rs_bindings_from_cc_cc_api
        --exclude=rs_bindings_from_cc_ir_matchers
        --exclude=rs_bindings_from_cc_ir_testing
        --exclude=rs_bindings_from_cc_multiplatform_ir_testing
        --exclude=rs_bindings_from_cc_test_generators

  test_cmake:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install ccache
      run: sudo apt-get update && sudo apt-get install -y ccache
    - name: Cache CMake with ccache
      uses: actions/cache@v5
      with:
        path: ~/.cache/ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-
    - name: Test CMake project
      run: |
        cd examples/build_systems/cmake
        cmake -B build -S . -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build --parallel
        cd build
        ctest --output-on-failure --parallel 2

  test_bazel:

    runs-on: ubuntu-latest
    env:
      HAS_BAZEL_CACHE_SECRET: ${{ secrets.BAZEL_CACHE_GCP_SERVICE_ACCOUNT_KEY != '' }}

    steps:
    - uses: actions/checkout@v6
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        cache-save: true
        external-cache: true
        repository-cache: true

    - name: 'Authenticate to Google Cloud'
      if: env.HAS_BAZEL_CACHE_SECRET == 'true'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.BAZEL_CACHE_GCP_SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Bazel Remote Cache flags'
      id: bazel_cache_flags
      run: |
        if [[ "$HAS_BAZEL_CACHE_SECRET" == "true" ]]; then
          echo "RCACHE_FLAGS=--remote_cache=https://storage.googleapis.com/CRUBIT_BUCKET_NAME --google_default_credentials" >> $GITHUB_ENV
          echo "Using GCS Remote Cache"
        else
          echo "RCACHE_FLAGS=" >> $GITHUB_ENV
          echo "Skipping GCS Remote Cache (no secret found)"
        fi

    - name: "Build Crubit using Bazel"
      run: >
        bazelisk build
        --lockfile_mode=error
        ${RCACHE_FLAGS}
        rs_bindings_from_cc:bazel_types
        rs_bindings_from_cc:cmdline_flags
        rs_bindings_from_cc:cc_ir
# LINT.ThenChange(//depot/copy.bara.sky)
